services:
  web:
    build: .
    ports:
      - "8010:8010"
    environment:
      SECRET_KEY: ${SECRET_KEY:-}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_ADMIN_PASS}
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
