services:
  web:
    build: .
    ports:
      - "8010:8010"
    environment:
      SECRET_KEY: ${SECRET_KEY:-}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_ADMIN_PASS}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-10.0.0.4}
      SCRIPT_NAME: /jc
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
