services:
  web:
    build:
      context: .
      args:
        CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
        DJANGO_ADMIN_PASS: ${DJANGO_ADMIN_PASS}
    ports:
      - "8010:8010"
    environment:
      SECRET_KEY: ${SECRET_KEY:-}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_ADMIN_PASS}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-10.0.0.4}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
