# Generated by Django 5.2.6 on 2025-09-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modifier', models.CharField(blank=True, max_length=100)),
                ('joules', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('name', 'modifier')},
            },
        ),
        migrations.CreateModel(
            name='FoodItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eaten_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.fooditemtemplate')),
            ],
        ),
    ]
